export const projectMessages = {
    pt: {
        title: 'Projetos',
        "timer": "Timer",
        "jogoDaVelha": "Jogo da Velha",
        "lineCare": "LineCare",
        "pomo": "POMO",
        "monitoramentoDeEnchentes": "Monitoramento de Enchentes",
        "shellPass": "ShellPass",
        "previsaoDeAtritoDeColaboradores": "Previsão de Atrito",
        "classificacaoDeIris": "Classificação de Íris",
        "olaMundoQuantico": "Olá, Mundo Quântico!",
        "superposicaoInterferenciaMedicoes": "Fundamentos de Quântica",
        "mitigacaoDeErrosQuantiocos": "Mitigação de Erros Quânticos",
        "hamiltonianoComSQDQuantico": "Hamiltoniano com SQD",
        "correcaoDeErrosQuanticos": "Correção de Erros Quânticos",
        "implementandoOIQFT": "Implementando o IQFT",
        "implementacaoDoProtocoloBB84": "Implementação do protocolo BB84",
        "competicaoCampusMobileClaro": "Competição Campus Mobile",
        "webPMGerenciadorDeProjetos": "WebPM",
        "doceConfeiteiro": "Doce Confeiteiro",
        "monitoramentoDeRiscosDeDeslizamentos": "Predição de Deslizamentos",
        "portfolio": "Portfólio"
    },
    en: {
        title: 'Projects',
        "timer": "Timer",
        "jogoDaVelha": "Tic-Tac-Toe Game",
        "lineCare": "LineCare",
        "pomo": "POMO",
        "monitoramentoDeEnchentes": "Flood Monitoring",
        "shellPass": "ShellPass",
        "previsaoDeAtritoDeColaboradores": "Attrition Prediction",
        "classificacaoDeIris": "Iris Classification",
        "olaMundoQuantico": "Hello, Quantum World!",
        "superposicaoInterferenciaMedicoes": "Fundamentals of Quantum",
        "mitigacaoDeErrosQuantiocos": "Quantum Error Mitigation",
        "hamiltonianoComSQDQuantico": "Hamiltonian with SQD",
        "correcaoDeErrosQuanticos": "Quantum Error Correction",
        "implementandoOIQFT": "Implementing the IQFT",
        "implementacaoDoProtocoloBB84": "BB84 Protocol Implementation",
        "competicaoCampusMobileClaro": "Campus Mobile Competition",
        "webPMGerenciadorDeProjetos": "WebPM",
        "doceConfeiteiro": "Sweet Confectioner",
        "monitoramentoDeRiscosDeDeslizamentos": "Landslide Risk Monitoring",
        "portfolio": "Portfolio"
    }
}