export const articlesData = {
    "Quântica": [
        {
            "id": 1,
            "titulo": "Implementação do protocolo BB84",
            "techs": ["Qiskit", "Numpy", "Matplotlib"],
            "link-github": "https://github.com/KaueMiziara/gjk-fallfest-ufabc-2025/blob/main/bb84.ipynb",
            "descrição": "descrição",
            "type": "quantica",
        },
        {
            "id": 1,
            "titulo": "Implementação do protocolo BB84",
            "techs": ["Qiskit", "Numpy", "Matplotlib"],
            "link-github": "https://github.com/KaueMiziara/gjk-fallfest-ufabc-2025/blob/main/bb84.ipynb",
            "descrição": "descrição",
            "type": "quantica",
        },
        {
            "id": 1,
            "titulo": "Implementação do protocolo BB84",
            "techs": ["Qiskit", "Numpy", "Matplotlib"],
            "link-github": "https://github.com/KaueMiziara/gjk-fallfest-ufabc-2025/blob/main/bb84.ipynb",
            "descrição": "descrição",
            "type": "quantica",
        },
        {
            "id": 1,
            "titulo": "Implementação do protocolo BB84",
            "techs": ["Qiskit", "Numpy", "Matplotlib"],
            "link-github": "https://github.com/KaueMiziara/gjk-fallfest-ufabc-2025/blob/main/bb84.ipynb",
            "descrição": "descrição",
            "type": "quantica",
        },
        {
            "id": 1,
            "titulo": "Implementação do protocolo BB84",
            "techs": ["Qiskit", "Numpy", "Matplotlib"],
            "link-github": "https://github.com/KaueMiziara/gjk-fallfest-ufabc-2025/blob/main/bb84.ipynb",
            "descrição": "descrição",
            "type": "quantica",
        },
        {
            "id": 1,
            "titulo": "Implementação do protocolo BB84",
            "techs": ["Qiskit", "Numpy", "Matplotlib"],
            "link-github": "https://github.com/KaueMiziara/gjk-fallfest-ufabc-2025/blob/main/bb84.ipynb",
            "descrição": "descrição",
            "type": "quantica",
        },
        {
            "id": 1,
            "titulo": "Implementação do protocolo BB84",
            "techs": ["Qiskit", "Numpy", "Matplotlib"],
            "link-github": "https://github.com/KaueMiziara/gjk-fallfest-ufabc-2025/blob/main/bb84.ipynb",
            "descrição": "descrição",
            "type": "quantica",
        },
        {
            "id": 1,
            "titulo": "Implementação do protocolo BB84",
            "techs": ["Qiskit", "Numpy", "Matplotlib"],
            "link-github": "https://github.com/KaueMiziara/gjk-fallfest-ufabc-2025/blob/main/bb84.ipynb",
            "descrição": "descrição",
            "type": "quantica",
        },
        {
            "id": 1,
            "titulo": "Implementação do protocolo BB84",
            "techs": ["Qiskit", "Numpy", "Matplotlib"],
            "link-github": "https://github.com/KaueMiziara/gjk-fallfest-ufabc-2025/blob/main/bb84.ipynb",
            "descrição": "descrição",
            "type": "quantica",
        },
        {
            "id": 1,
            "titulo": "Implementação do protocolo BB84",
            "techs": ["Qiskit", "Numpy", "Matplotlib"],
            "link-github": "https://github.com/KaueMiziara/gjk-fallfest-ufabc-2025/blob/main/bb84.ipynb",
            "descrição": "descrição",
            "type": "quantica",
        },
        {
            "id": 1,
            "titulo": "Implementação do protocolo BB84",
            "techs": ["Qiskit", "Numpy", "Matplotlib"],
            "link-github": "https://github.com/KaueMiziara/gjk-fallfest-ufabc-2025/blob/main/bb84.ipynb",
            "descrição": "descrição",
            "type": "quantica",
        },
        {
            "id": 1,
            "titulo": "Implementação do protocolo BB84",
            "techs": ["Qiskit", "Numpy", "Matplotlib"],
            "link-github": "https://github.com/KaueMiziara/gjk-fallfest-ufabc-2025/blob/main/bb84.ipynb",
            "descrição": "descrição",
            "type": "quantica",
        }
    ]
}